/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ahfinder;

import ahfinder.link.Retriever;

import java.io.IOException;
import java.util.List;

public class App {

    public static void main(String[] args) {

        Retriever retriever = new Retriever();
        try {
            List<String> linksOnWebsite = retriever.retrieveLinksFrom("https://en.wikipedia.org/wiki/Gloster_Meteor");
            for (String link : linksOnWebsite) {
                System.out.println(link);
            }
            System.out.println("end.");
        } catch (IOException e) {
            e.printStackTrace();
        }

    }
}
